import { useEffect } from 'react';
import { toCents, fmtDate, affiliateUrl } from '../utils/formatters';

export default function MarketDetailDrawer({ signal, onClose }) {
  useEffect(() => {
    const handler = (e) => { if (e.key === 'Escape') onClose(); };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [onClose]);

  if (!signal) return null;

  const kp = signal.platforms?.kalshi;
  const pp = signal.platforms?.polymarket;

  return (
    <>
      {/* Backdrop */}
      <div style={styles.backdrop} onClick={onClose} />

      {/* Drawer */}
      <div style={styles.drawer}>
        <div style={styles.drawerHeader}>
          <div style={styles.drawerTitle}>{signal.title}</div>
          <button style={styles.closeBtn} onClick={onClose} aria-label="Close">✕</button>
        </div>

        <div style={styles.drawerBody}>
          {/* Signal summary */}
          <Section title="Prophet Signal">
            <Row label="Side">
              <span style={signal.side === 'BUY_YES' ? styles.buyBadge : styles.passBadge}>
                {signal.side === 'BUY_YES' ? 'BUY YES' : signal.side === 'BUY_NO' ? 'BUY NO' : 'PASS'}
              </span>
            </Row>
            <Row label="Entry price">{toCents(signal.price)}</Row>
            <Row label="Confidence">{Math.round((signal.confidence ?? 0) * 100)}%</Row>
            <Row label="Kelly size">{signal.kelly_pct?.toFixed(1) ?? '—'}% of balance</Row>
            <Row label="Arb edge">{signal.arb_edge_pct > 0 ? `${signal.arb_edge_pct}%` : '—'}</Row>
            <Row label="Price gap">{signal.price_gap > 0 ? `${Math.round(signal.price_gap * 100)}¢` : '—'}</Row>
          </Section>

          {/* Rationale */}
          <Section title="Rationale">
            <p style={styles.reason}>{signal.reason || 'No rationale available.'}</p>
          </Section>

          {/* Platform prices */}
          <Section title="Platform Prices">
            {kp && (
              <div style={styles.platRow}>
                <span style={styles.platName}>Kalshi</span>
                <span style={styles.platPrice}>YES {toCents(kp.yes_price)} / NO {toCents(kp.no_price)}</span>
                <a href={affiliateUrl(kp.url, 'kalshi')} target="_blank" rel="noopener noreferrer" style={styles.platLink}>
                  Trade →
                </a>
              </div>
            )}
            {pp && (
              <div style={styles.platRow}>
                <span style={styles.platName}>Polymarket</span>
                <span style={styles.platPrice}>YES {toCents(pp.yes_price)} / NO {toCents(pp.no_price)}</span>
                <a href={affiliateUrl(pp.url, 'polymarket')} target="_blank" rel="noopener noreferrer" style={styles.platLink}>
                  Trade →
                </a>
              </div>
            )}
          </Section>

          {/* Meta */}
          <Section title="Market Info">
            <Row label="Category">{signal.category || '—'}</Row>
            <Row label="Match type">{signal.source || '—'}</Row>
            {signal.resolution_date && (
              <Row label="Resolves">{fmtDate(signal.resolution_date)}</Row>
            )}
          </Section>

          <p style={styles.disclaimer}>
            Not financial advice. Signals are generated by an automated strategy and may be wrong.
            Always do your own research before trading.
          </p>
        </div>
      </div>
    </>
  );
}

function Section({ title, children }) {
  return (
    <div style={styles.section}>
      <div style={styles.sectionTitle}>{title}</div>
      {children}
    </div>
  );
}

function Row({ label, children }) {
  return (
    <div style={styles.dataRow}>
      <span style={styles.dataLabel}>{label}</span>
      <span style={styles.dataValue}>{children}</span>
    </div>
  );
}

const styles = {
  backdrop: {
    position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.6)', zIndex: 40,
  },
  drawer: {
    position: 'fixed', top: 0, right: 0, bottom: 0, width: '420px', maxWidth: '90vw',
    background: 'var(--bg-secondary)', borderLeft: '1px solid var(--border)',
    zIndex: 50, display: 'flex', flexDirection: 'column', overflowY: 'auto',
    boxShadow: '-8px 0 32px rgba(0,0,0,0.4)',
  },
  drawerHeader: {
    display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between',
    gap: '12px', padding: '20px 20px 16px', borderBottom: '1px solid var(--border)',
    background: 'var(--bg-card)',
  },
  drawerTitle: {
    fontSize: '14px', fontWeight: 700, color: 'var(--text-primary)',
    fontFamily: 'var(--font-sans)', lineHeight: 1.4, flex: 1,
  },
  closeBtn: {
    background: 'none', border: 'none', color: 'var(--text-muted)', fontSize: '16px',
    cursor: 'pointer', padding: '0 4px', lineHeight: 1, flexShrink: 0,
  },
  drawerBody: { padding: '16px 20px', flex: 1 },

  section:      { marginBottom: '24px' },
  sectionTitle: { fontSize: '10px', fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.8px', marginBottom: '10px', fontFamily: 'var(--font-sans)' },

  dataRow:   { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '6px 0', borderBottom: '1px solid rgba(30,41,59,0.4)' },
  dataLabel: { fontSize: '12px', color: 'var(--text-muted)', fontFamily: 'var(--font-sans)' },
  dataValue: { fontSize: '13px', fontWeight: 600, color: 'var(--text-primary)', fontFamily: 'var(--font-mono)' },

  buyBadge:  { fontFamily: 'var(--font-mono)', fontSize: '12px', fontWeight: 700, background: 'var(--accent-green-dim)', color: 'var(--accent-green)', padding: '3px 10px', borderRadius: '4px' },
  passBadge: { fontFamily: 'var(--font-mono)', fontSize: '12px', fontWeight: 600, background: 'rgba(255,255,255,0.04)', color: 'var(--text-muted)', padding: '3px 10px', borderRadius: '4px' },

  reason: { fontSize: '13px', color: 'var(--text-secondary)', fontFamily: 'var(--font-mono)', lineHeight: 1.6, margin: 0 },

  platRow:   { display: 'flex', alignItems: 'center', gap: '10px', padding: '8px 0', borderBottom: '1px solid rgba(30,41,59,0.4)' },
  platName:  { fontSize: '12px', fontWeight: 700, color: 'var(--text-primary)', fontFamily: 'var(--font-sans)', width: '90px', flexShrink: 0 },
  platPrice: { fontSize: '12px', color: 'var(--text-secondary)', fontFamily: 'var(--font-mono)', flex: 1 },
  platLink:  { fontSize: '12px', color: 'var(--accent-green)', fontWeight: 600, fontFamily: 'var(--font-sans)', textDecoration: 'none' },

  disclaimer: { fontSize: '11px', color: 'var(--text-muted)', fontFamily: 'var(--font-sans)', lineHeight: 1.5, marginTop: '24px', padding: '12px', background: 'rgba(255,255,255,0.03)', borderRadius: '6px', border: '1px solid var(--border)' },
};
