// Desk team-code (ISO3-ish, from match_id) -> flag ISO2 filename in /flags.
//
// Keep this map in sync with `desk/desk/sports/football/flags.py`
// (`TEAM_CODE_TO_ISO2`) — that file is the Python-side source of truth
// used by `site/generate.py` for the static site. The two render
// paths share the same /flags/*.svg assets.
export const TEAM_FLAG = {
  "alg": "dz",
  "arg": "ar",
  "aus": "au",
  "aut": "at",
  "bel": "be",
  "bih": "ba",
  "bra": "br",
  "can": "ca",
  "che": "ch",
  "civ": "ci",
  "cod": "cd",
  "col": "co",
  "cpv": "cv",
  "cro": "hr",
  "cuw": "cw",
  "cze": "cz",
  "ecu": "ec",
  "egy": "eg",
  "eng": "gb-eng",
  "esp": "es",
  "fra": "fr",
  "ger": "de",
  "gha": "gh",
  "hai": "ht",
  "irn": "ir",
  "irq": "iq",
  "jor": "jo",
  "jpn": "jp",
  "kor": "kr",
  "ksa": "sa",
  "mar": "ma",
  "mex": "mx",
  "ned": "nl",
  "nor": "no",
  "nzl": "nz",
  "pan": "pa",
  "par": "py",
  "por": "pt",
  "qat": "qa",
  "rsa": "za",
  "sco": "gb-sct",
  "sen": "sn",
  "swe": "se",
  "tun": "tn",
  "tur": "tr",
  "uru": "uy",
  "usa": "us",
  "uzb": "uz",
  "nga": "ng",
  "cmr": "cm",
  "crc": "cr",
  "den": "dk",
  "fin": "fi",
  "irl": "ie",
  "isl": "is",
  "ita": "it",
  "jam": "jm",
  "hon": "hn",
  "mli": "ml",
  "nir": "gb-nir",
  "per": "pe",
  "pol": "pl",
  "prk": "kp",
  "rou": "ro",
  "srb": "rs",
  "uae": "ae",
  "ven": "ve",
  "wal": "gb-wls",
  "chi": "cl",
  "alb": "al",
  "bol": "bo"
};
